package com.project.fitness.repository;

import com.project.fitness.model.Activity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ActivityRepository extends JpaRepository<Activity, String> {
    List<Activity> findByUserId(String userId); // at runtime this method's query is generated by Jpa using Hibernate,
                                                // naming conventions must be followed
}
